### PR TITLE
Ipv6 pxe

### PR DESCRIPTION
**Pull request by DavidDecotigny**
a couple tiny fixes, thanks!

### CODE REVIEW

**Comment by sammj** [comment]
Hey David, nice one! I'll merge this here in my tree for building purposes, but do you want to send these to the Busybox mailing list as well?

**Comment by DavidDecotigny** [comment]
uploaded another PR that I prefer to clearing the d6_packet.
I can also send the 3 patches to the ml, but without your patches as well, I don't know it will make much sense. How are you upstreaming this branch, usually? I would be happy if you added those patches to your stack of patches you upstream to master.

**Comment by sammj** [comment]
@DavidDecotigny my changes are already upstream so yours should be fine on their own.

**Comment by DavidDecotigny** [comment]
git send-email done, you should be cc. I'm not a subscriber to the ml, so it might get rejected. No bounce for now, so I don't know (yet) if it went through.

**Pull request merged**
